# Generated by Django 4.0.4 on 2022-09-12 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('spt_ltp', models.FloatField()),
                ('lukr_mwkr', models.FloatField()),
                ('fopnr_anti', models.FloatField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('series', models.IntegerField(blank=True, null=True)),
                ('methods', models.TextField(blank=True, null=True)),
                ('details', models.IntegerField(blank=True, null=True)),
                ('tools', models.IntegerField(blank=True, null=True)),
                ('redis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_number', models.IntegerField()),
                ('detail_stanok_number', models.IntegerField()),
                ('detail_time', models.IntegerField()),
                ('detail_turn', models.IntegerField(blank=True, null=True)),
                ('redis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
            },
        ),
        migrations.CreateModel(
            name='ArchiveLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.TextField(blank=True, null=True)),
                ('method', models.TextField()),
                ('rating', models.TextField()),
                ('details', models.IntegerField()),
                ('tools', models.IntegerField()),
                ('series', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_number', models.IntegerField()),
                ('detail_tools_number', models.IntegerField()),
                ('detail_time', models.IntegerField()),
                ('record_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.archiveletter')),
            ],
        ),
    ]
